server.port=8081

spring.security.enabled=false

spring.security.filter.order=0
# Configuracion SpringDoc Swagger/OpenAPI  
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.show-actuator=true

#Personalizar Swagger UI
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.doc-expansion=none
# escanear el paquete correcto
springdoc.packages-to-scan=cl.bne.curriculardata.api
springdoc.paths-to-match=/api/**

# URLs de la documentación
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración de la UI
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.cl.bne.curriculardata=DEBUG